name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "platform-tools"

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3

      - name: Build & unit test
        run: ./gradlew clean test assembleDebug
